"""fixed model

Revision ID: 72b6a5ad6b01
Revises: e340cbb0ba77
Create Date: 2024-09-02 18:31:45.071348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b6a5ad6b01'
down_revision = 'e340cbb0ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
